/**
 * Export and sharing utilities
 */

import type { Feedback, Session } from '@/types';
import { formatDuration, formatDate, formatScore } from './format';

/**
 * Generate a shareable text summary of feedback
 * @param feedback - Feedback data
 * @param session - Optional session data
 * @returns Formatted text summary
 */
export function generateFeedbackSummary(
  feedback: Feedback,
  session?: Session
): string {
  const lines: string[] = [];

  // Header
  lines.push('🎯 AI Conversation Coach - Feedback Summary');
  lines.push('━'.repeat(50));
  lines.push('');

  // Session info
  if (session) {
    lines.push(`📅 Date: ${formatDate(session.created_at)}`);
    if (session.duration_seconds) {
      lines.push(`⏱️  Duration: ${formatDuration(session.duration_seconds)}`);
    }
    lines.push('');
  }

  // Scores
  lines.push('📊 Your Scores:');
  lines.push(`  Clarity:     ${formatScore(feedback.clarity_score)}/10`);
  lines.push(`  Confidence:  ${formatScore(feedback.confidence_score)}/10`);
  lines.push(`  Empathy:     ${formatScore(feedback.empathy_score)}/10`);
  lines.push(`  Pacing:      ${formatScore(feedback.pacing_score)}/10`);
  lines.push('');

  // Metrics
  lines.push('📈 Metrics:');
  lines.push(`  Words per minute: ${feedback.words_per_minute}`);
  lines.push(`  Filler words: ${feedback.filler_count}`);
  if (feedback.detailed_analysis?.question_ratio) {
    lines.push(`  Question ratio: ${feedback.detailed_analysis.question_ratio.toFixed(1)}%`);
  }
  lines.push('');

  // Summary
  lines.push('💬 Summary:');
  lines.push(feedback.summary);
  lines.push('');

  // Strengths
  if (feedback.strengths && feedback.strengths.length > 0) {
    lines.push('✅ What You Did Well:');
    feedback.strengths.forEach((strength, index) => {
      lines.push(`  ${index + 1}. ${strength}`);
    });
    lines.push('');
  }

  // Improvements
  if (feedback.improvements && feedback.improvements.length > 0) {
    lines.push('⚡ Areas to Improve:');
    feedback.improvements.forEach((improvement, index) => {
      lines.push(`  ${index + 1}. ${improvement}`);
    });
    lines.push('');
  }

  // Practice drill
  if (feedback.practice_drill) {
    lines.push('🎯 Practice Drill:');
    lines.push(feedback.practice_drill);
    lines.push('');
  }

  // Footer
  lines.push('━'.repeat(50));
  lines.push('Generated by AI Conversation Coach');
  lines.push(`© ${new Date().getFullYear()} AI Conversation Coach`);

  return lines.join('\n');
}

/**
 * Generate a detailed feedback report (longer format)
 * @param feedback - Feedback data
 * @param session - Optional session data
 * @returns Detailed formatted report
 */
export function generateDetailedReport(
  feedback: Feedback,
  session?: Session
): string {
  const summary = generateFeedbackSummary(feedback, session);

  const additionalLines: string[] = [];

  // Add detailed analysis if available
  if (feedback.detailed_analysis) {
    additionalLines.push('');
    additionalLines.push('📋 Detailed Analysis');
    additionalLines.push('━'.repeat(50));

    // Filler words breakdown
    if (feedback.detailed_analysis.filler_words && feedback.detailed_analysis.filler_words.length > 0) {
      additionalLines.push('');
      additionalLines.push('Filler Words Breakdown:');
      feedback.detailed_analysis.filler_words.forEach(({ word, count }) => {
        additionalLines.push(`  "${word}": ${count} times`);
      });
    }

    // Tone analysis
    if (feedback.detailed_analysis.tone_analysis) {
      additionalLines.push('');
      additionalLines.push('Tone Analysis:');
      additionalLines.push(`  ${feedback.detailed_analysis.tone_analysis}`);
    }

    // Structure quality
    if (feedback.detailed_analysis.structure_quality) {
      additionalLines.push('');
      additionalLines.push('Structure Quality:');
      additionalLines.push(`  ${feedback.detailed_analysis.structure_quality}`);
    }

    // Active listening
    if (feedback.detailed_analysis.active_listening_score) {
      additionalLines.push('');
      additionalLines.push('Active Listening:');
      additionalLines.push(`  Score: ${formatScore(feedback.detailed_analysis.active_listening_score)}/10`);
    }
  }

  return summary + additionalLines.join('\n');
}

/**
 * Generate CSV export of feedback metrics
 * @param feedbackList - Array of feedback records
 * @returns CSV formatted string
 */
export function generateFeedbackCSV(feedbackList: Feedback[]): string {
  const headers = [
    'Date',
    'Clarity Score',
    'Confidence Score',
    'Empathy Score',
    'Pacing Score',
    'Words Per Minute',
    'Filler Count',
    'Summary',
  ];

  const rows: string[][] = [headers];

  feedbackList.forEach((feedback) => {
    rows.push([
      formatDate(feedback.created_at),
      formatScore(feedback.clarity_score),
      formatScore(feedback.confidence_score),
      formatScore(feedback.empathy_score),
      formatScore(feedback.pacing_score),
      feedback.words_per_minute.toString(),
      feedback.filler_count.toString(),
      `"${feedback.summary.replace(/"/g, '""')}"`, // Escape quotes
    ]);
  });

  return rows.map(row => row.join(',')).join('\n');
}

/**
 * Generate markdown export of feedback
 * @param feedback - Feedback data
 * @param session - Optional session data
 * @returns Markdown formatted string
 */
export function generateMarkdownReport(
  feedback: Feedback,
  session?: Session
): string {
  const lines: string[] = [];

  // Header
  lines.push('# AI Conversation Coach - Feedback Report');
  lines.push('');

  // Session info
  if (session) {
    lines.push(`**Date:** ${formatDate(session.created_at)}`);
    if (session.duration_seconds) {
      lines.push(`**Duration:** ${formatDuration(session.duration_seconds)}`);
    }
    lines.push('');
  }

  // Scores table
  lines.push('## Your Scores');
  lines.push('');
  lines.push('| Metric | Score |');
  lines.push('|--------|-------|');
  lines.push(`| Clarity | ${formatScore(feedback.clarity_score)}/10 |`);
  lines.push(`| Confidence | ${formatScore(feedback.confidence_score)}/10 |`);
  lines.push(`| Empathy | ${formatScore(feedback.empathy_score)}/10 |`);
  lines.push(`| Pacing | ${formatScore(feedback.pacing_score)}/10 |`);
  lines.push('');

  // Metrics
  lines.push('## Metrics');
  lines.push('');
  lines.push(`- **Words per minute:** ${feedback.words_per_minute}`);
  lines.push(`- **Filler words:** ${feedback.filler_count}`);
  if (feedback.detailed_analysis?.question_ratio) {
    lines.push(`- **Question ratio:** ${feedback.detailed_analysis.question_ratio.toFixed(1)}%`);
  }
  lines.push('');

  // Summary
  lines.push('## Summary');
  lines.push('');
  lines.push(feedback.summary);
  lines.push('');

  // Strengths
  if (feedback.strengths && feedback.strengths.length > 0) {
    lines.push('## ✅ What You Did Well');
    lines.push('');
    feedback.strengths.forEach((strength, index) => {
      lines.push(`${index + 1}. ${strength}`);
    });
    lines.push('');
  }

  // Improvements
  if (feedback.improvements && feedback.improvements.length > 0) {
    lines.push('## ⚡ Areas to Improve');
    lines.push('');
    feedback.improvements.forEach((improvement, index) => {
      lines.push(`${index + 1}. ${improvement}`);
    });
    lines.push('');
  }

  // Practice drill
  if (feedback.practice_drill) {
    lines.push('## 🎯 Practice Drill');
    lines.push('');
    lines.push(feedback.practice_drill);
    lines.push('');
  }

  // Footer
  lines.push('---');
  lines.push('');
  lines.push(`*Generated by AI Conversation Coach on ${formatDate(new Date())}*`);

  return lines.join('\n');
}
